out_dir: 'runs/exp_symcif_v1'
eval_interval: 250
eval_iters_train: 200
eval_iters_val: 200
log_interval: 1
always_save_checkpoint: True
validate: True

dataset: 'data/tokens_symcif_v1'
gradient_accumulation_steps: 4
batch_size: 32
block_size: 1024

n_layer: 8
n_head: 8
n_embd: 512
dropout: 0.1

learning_rate: 1e-3
decay_lr: True
max_iters: 3500
lr_decay_iters: 3500
min_lr: 1e-4
beta2: 0.99
warmup_iters: 100

seed: 1337
device: 'cuda:0'
dtype: 'bfloat16'
compile: True

sampling_temperature: 0.8
sampling_top_k: 10
sampling_max_new_tokens: 2048
