out_dir: 'runs/exp_symcif_v2_full_large'
eval_interval: 250
eval_iters_train: 100
eval_iters_val: 100
log_interval: 1
always_save_checkpoint: True
validate: True

dataset: 'data/tokens_symcif_v2'
gradient_accumulation_steps: 1
batch_size: 64
block_size: 1024

n_layer: 12
n_head: 12
n_embd: 768
dropout: 0.1

learning_rate: 6e-4
decay_lr: True
max_iters: 2000
lr_decay_iters: 2000
min_lr: 6e-5
beta2: 0.95
warmup_iters: 100

seed: 1337
device: 'cuda:0'
dtype: 'bfloat16'
compile: True

sampling_temperature: 0.8
sampling_top_k: 10
sampling_max_new_tokens: 2048
